# -*- coding: utf-8 -*-
"""HeartDeseasePrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i93LQiH2IcSG_HVH2y-wis_6qyyylAMS
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

data = pd.read_csv('/heart.csv')

data.head()

data.shape

data.describe()

data.isnull()

data.isnull().sum()

data.info()

sns.countplot(x='target', data=data)

sns.countplot(x='target', hue='sex', data=data)   # 1-male, 0-female

sns.countplot(x='target', hue='cp', data=data)

sns.countplot(x='target', hue='fbs', data=data)

"""'fbs' feature is not affected very much for target.so we can eliminate that feature."""

# Drop the column 'fbs'
column_to_remove = 'fbs'
data = data.drop(columns=[column_to_remove])

# Save the updated DataFrame to a new CSV file
data.to_csv('/updated_heart.csv', index=False)

sns.countplot(x='target', hue='exang', data=data)

sns.countplot(x='target', hue='slope', data=data)

sns.countplot(x='target', hue='ca', data=data)

sns.countplot(x='target', hue='thal', data=data)

sns.countplot(x='target', hue='restecg', data=data)

data.hist('age')

data.hist('trestbps')

data.hist('chol')

data.hist('thalach')

data.hist('oldpeak')

# shuffle data
data = data.sample(frac=1)
data = data.reset_index(drop=True)  # reset index after shuffling

data.head()

X = data.drop('target', axis=1) # use all columns except 'target' as features
Y = data['target']

print(X.shape)
print(Y.shape)

X

Y

# split train and test data
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train,  Y_test = train_test_split(X, Y, test_size=0.25, stratify=Y, random_state=2)
# stratify will use even amount of different targets

X_train.shape,  X_test.shape

"""# Logistic Regression"""

# use of cross validation technique
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
log_model_cv = LogisticRegression()

# cross validation with 5 folds
cv_scores = cross_val_score(log_model_cv, X_train, Y_train, cv=5)

# Print the cross-validation scores
print("Cross-validation scores:", cv_scores)
print("Mean CV score:", np.mean(cv_scores))

# use Logistic Regression model
from sklearn.linear_model import LogisticRegression
log_model = LogisticRegression()

# train the model
log_model.fit(X_train, Y_train)

# Check if the model converged
print(f"Number of iterations: {log_model.n_iter_}")

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
import joblib



scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Save the scaler to a file
joblib.dump(scaler, '/scaler.pkl')

# Train the Logistic Regression model
log_model = LogisticRegression(max_iter=1000)  # Increase the number of iterations
log_model.fit(X_train_scaled, Y_train)

# checking the accuracy on training data
Train_pred = log_model.predict(X_train_scaled)

from sklearn.metrics import accuracy_score
train_acc = accuracy_score(Y_train, Train_pred)
print("Accuracy on training data = ", train_acc)

# predict test data
predictions = log_model.predict(X_test_scaled)


# evaluate the model

accuracy_score(Y_test, predictions)

import joblib

# Load the scaler and model from file
scaler = joblib.load('/scaler.pkl')

# build a prediction for user input
input_data = (34,0,1,118,210,1,192,0,0.7,2,0,2)
input_arr = np.asarray(input_data)

#reshape the array to predict only one instance
input_reshaped = input_arr.reshape(1,-1)


# Apply the same scaling as used for the training data
input_scaled = scaler.transform(input_reshaped)


import warnings
warnings.filterwarnings("ignore", category=UserWarning)

# predict
prediction = log_model.predict(input_scaled)

if prediction == [1]:
  print('Heart Disease - Yes')
else:
  print('Heart Disease - No')

# save model
import joblib

file_path = '/logistic_regression_model.pkl'

# Save the model to the file path
joblib.dump(log_model, file_path)

print("Model saved successfully!")